version: '2'

services:
  api:
    container_name: Api-Container
    build: .
    ports:
      - 80:8080
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: DB-Container
    image: mongo:latest
    ports:
      - 27017:27017